[hotkeys]
mod = Alt
altTab = Tab
close = mod+F4
maximize = mod+m
minimize = mod+n
launcher = mod+space
fullscreen = F11

[exec]
alt+z = okr > /dev/null 2&>1
super+z = okr2 > /dev/null 2&>1
alt+a = web > /dev/null 2&>1
alt+c = cache > /dev/null 2&>1
alt+d = pkill -15 -u rustam
alt+f = spoweroff > /dev/null 2&>1
alt+F10 = screenrecorder > /dev/null 2&>1
alt+g = rg > /dev/null 2&>1
alt+q = backup
alt+r = qterminal -e 'watch -n 99000000 xdotool getmouselocation'
alt+s = sreboot > /dev/null 2&>1
alt+v = daypl > /dev/null 2&>1
alt+x = bluetooth > /dev/null 2&>1
super+a = sudo acpiconf -s 3
super+c = close_windows
super+tab = xdotool search --onlyvisible --class '.*' windowminimize %@
print = scrot /home/rustam/Изображения/screen.png

[icons]
dir = /home/rustam/.icons/apps

[appearance]
titlebar_height = 24
button_size = 16
icon_left = true
alttab_position = center
alttab_icon_size = 64
titlebar_color = #000000
alttab_bg_color = #000000

[general]
launcher_cmd = dmenu_run
